import type { Step } from "./types";

/**
 * Fonte da verdade do questionário. Adicionar pergunta = editar este arquivo
 * (sem migração: respostas ficam em answers JSONB, chaveadas por question.id).
 *
 * Todos os rótulos, ajudas, exemplos, descrições e subtítulos vêm da seção
 * 7.1 do BRIEFING_SPEC.md, exatamente como escritos lá. `help` e `subtitle`
 * são obrigatórios no tipo — o build falha se faltarem.
 */
export const STEPS: Step[] = [
  {
    id: "contato",
    title: "Vamos nos conhecer",
    subtitle: "Só o básico para começarmos. Leva menos de 1 minuto.",
    estimatedMinutes: 1,
    questions: [
      { id: "name", type: "text", label: "Qual é o seu nome?", help: "Para sabermos como te chamar durante o projeto.", placeholder: "Como podemos te chamar?", required: true },
      { id: "company", type: "text", label: "Qual o nome da sua empresa ou marca?", help: "Se ainda não tem um nome definido, escreva o que pretende usar ou o seu próprio nome.", placeholder: "Nome do negócio", required: true },
      { id: "whatsapp", type: "phone", label: "Qual o seu WhatsApp?", help: "É por onde vamos falar com você sobre o projeto. Coloque com DDD.", placeholder: "(00) 90000-0000", required: true },
      { id: "email", type: "email", label: "Qual o seu e-mail?", help: "Vamos usar para enviar propostas e arquivos. Prefira um que você olha com frequência.", placeholder: "voce@empresa.com", required: true },
      { id: "current_site", type: "url", label: "Você já tem um site? Qual o endereço?", help: "Se já tem, cole o link para vermos como está hoje. Se não tem, é só pular.", example: "www.suaempresa.com.br" },
      { id: "socials", type: "links", label: "Quais são as suas redes sociais?", help: "Cole os links do seu Instagram, LinkedIn, etc. Isso nos ajuda a entender o estilo da sua marca e a colocar esses links no site.", placeholder: "www.exemplo.com.br", maxItems: 5 },
    ],
  },
  {
    id: "tipo",
    title: "O que vamos construir?",
    subtitle: "Escolha o que mais se parece com o que você imagina. Se ficar na dúvida, a gente ajuda depois.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "project_type",
        type: "cards",
        label: "Que tipo de projeto você precisa?",
        help: "Escolha o que mais se parece com o que você tem em mente. Se estiver em dúvida, escolha \"Outro\" e explique nas próximas telas.",
        required: true,
        options: [
          { value: "landing", label: "Landing page", description: "Uma página única, focada em uma ação, como vender ou captar contatos." },
          { value: "institucional", label: "Site institucional", description: "Um site com várias páginas apresentando a sua empresa." },
          { value: "saas", label: "SaaS / sistema web", description: "Um sistema online com login, onde as pessoas usam uma ferramenta sua pelo navegador." },
          { value: "ecommerce", label: "E-commerce", description: "Uma loja virtual para vender produtos pela internet." },
          { value: "redesign", label: "Redesign", description: "Você já tem um site e quer refazê-lo." },
          { value: "outro", label: "Outro", description: "Algo diferente. Você explica nas próximas telas." },
        ],
      },
    ],
  },
  {
    id: "negocio",
    title: "Sobre o seu negócio",
    subtitle: "Quanto melhor entendermos o seu negócio, melhor o site vai conversar com os seus clientes. Pode escrever ou falar.",
    estimatedMinutes: 2,
    questions: [
      {
        id: "niche",
        type: "single",
        label: "Em qual segmento você atua?",
        help: "Escolha a área do seu negócio. Isso muda algumas perguntas que faremos em seguida.",
        options: [
          { value: "saude", label: "Saúde" },
          { value: "juridico", label: "Jurídico" },
          { value: "financeiro", label: "Financeiro" },
          { value: "educacao", label: "Educação" },
          { value: "tecnologia", label: "Tecnologia" },
          { value: "alimentacao", label: "Alimentação" },
          { value: "varejo", label: "Varejo" },
          { value: "servicos_locais", label: "Serviços locais" },
          { value: "imobiliario", label: "Imobiliário" },
          { value: "outro", label: "Outro" },
        ],
      },
      { id: "business_description", type: "textarea", label: "O que a sua empresa faz?", help: "Explique como se estivesse contando para um amigo: o que você vende ou oferece. Pode escrever ou gravar um áudio.", example: "Somos uma clínica de fisioterapia que atende idosos em casa.", placeholder: "Descreva em poucas linhas…", allowAudio: true },
      { id: "differentiator", type: "textarea", label: "O que te diferencia dos concorrentes?", help: "O que faz alguém escolher você e não outra empresa? Pode ser preço, atendimento, qualidade, rapidez, experiência...", example: "Entregamos em até 2 horas e temos atendimento humano 24h.", placeholder: "Por que escolhem você e não o concorrente?", allowAudio: true },
      { id: "problem_solved", type: "textarea", label: "Que problema você resolve para o seu cliente?", help: "Qual dificuldade a pessoa tem antes de te procurar, e como você ajuda a resolver?", example: "Pessoas sem tempo para cozinhar, que recebem refeições saudáveis prontas.", placeholder: "Qual dor do cliente você elimina?", allowAudio: true },
    ],
  },
  {
    id: "objetivo",
    title: "Qual o objetivo principal?",
    subtitle: "Todo site precisa de um foco principal. Isso guia o design inteiro.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "main_goal",
        type: "cards",
        label: "Qual o principal objetivo do projeto?",
        help: "Escolha só uma. É a coisa mais importante que você quer que o site faça. Isso deixa o design muito mais eficiente.",
        required: true,
        options: [
          { value: "vender", label: "Vender", description: "As pessoas comprando direto pelo site." },
          { value: "leads", label: "Captar leads", description: "As pessoas deixando nome e contato para você falar depois." },
          { value: "agendar", label: "Agendar atendimentos", description: "As pessoas marcando horário ou consulta." },
          { value: "apresentar", label: "Apresentar a empresa", description: "Mostrar quem você é e passar confiança." },
          { value: "validar", label: "Validar uma ideia", description: "Testar se a sua ideia interessa ao mercado antes de investir mais." },
          { value: "outro", label: "Outro", description: "Você explica melhor mais adiante." },
        ],
      },
    ],
  },
  {
    id: "publico",
    title: "Para quem é?",
    subtitle: "Um site bom é feito para uma pessoa específica, não para todo mundo.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "audience_type",
        type: "single",
        label: "Você vende para empresas, para pessoas ou para os dois?",
        help: "\"Empresas\" quer dizer que seu cliente é outro negócio (o famoso B2B). \"Pessoas\" é o consumidor final (B2C).",
        options: [
          { value: "b2b", label: "Empresas (B2B)" },
          { value: "b2c", label: "Consumidor final (B2C)" },
          { value: "ambos", label: "Ambos" },
        ],
      },
      { id: "audience_profile", type: "textarea", label: "Como é o seu cliente ideal?", help: "Descreva quem mais compra de você: profissão, idade, o que gosta, onde mora. Quanto mais detalhes, melhor.", example: "Mulheres de 30 a 45 anos, mães, que trabalham fora e valorizam praticidade.", placeholder: "Idade, perfil, hábitos…", allowAudio: true },
      {
        id: "age_range",
        type: "multi",
        label: "Qual a faixa de idade dele?",
        help: "Você pode marcar mais de uma.",
        options: [
          { value: "18-24", label: "18–24" },
          { value: "25-34", label: "25–34" },
          { value: "35-44", label: "35–44" },
          { value: "45-59", label: "45–59" },
          { value: "60+", label: "60+" },
        ],
      },
      {
        id: "region",
        type: "single",
        label: "Onde estão os seus clientes?",
        help: "Só na sua cidade, no estado, no país inteiro ou no mundo todo? Isso muda como o site é pensado.",
        options: [
          { value: "local", label: "Na minha cidade/região" },
          { value: "estadual", label: "No meu estado" },
          { value: "nacional", label: "No Brasil todo" },
          { value: "internacional", label: "Fora do Brasil também" },
        ],
      },
    ],
  },
  {
    id: "visual",
    title: "Identidade visual",
    subtitle: "Aqui entendemos o visual da sua marca. Se ainda não tem nada definido, sem problema: a gente cuida disso.",
    estimatedMinutes: 2,
    questions: [
      {
        id: "has_logo",
        type: "single",
        label: "Você já tem um logo?",
        help: "O logo é o símbolo ou o nome estilizado da sua marca. Se você tem, poderá enviar mais adiante.",
        options: [
          { value: "tenho", label: "Sim, tenho" },
          { value: "nao_tenho", label: "Não tenho" },
          { value: "criar", label: "Preciso criar uma" },
        ],
      },
      { id: "brand_colors", type: "colors", label: "Quais são as cores da sua marca?", help: "Se o seu logo já tem cores, escolha-as aqui. Se não tem nada definido, marque \"Não tenho, me sugira\" que a gente escolhe combinações para você.", unknownLabel: "Não tenho, me sugira" },
      { id: "brand_fonts", type: "text", label: "Quais fontes (tipos de letra) a sua marca usa?", help: "Se você não sabe o que é isso, sem problema: marque \"Não sei\" e escolhemos letras que combinem com a sua marca.", placeholder: "Ex.: Montserrat, serifada…", allowUnknown: true },
      { id: "refs_liked", type: "links", label: "Cole até 3 sites que você acha bonitos", help: "Podem ser de qualquer área, até de concorrentes. Servem de inspiração para entendermos o seu gosto. Não vamos copiar nenhum deles.", example: "www.exemplo.com.br", placeholder: "www.exemplo.com.br", maxItems: 3 },
      { id: "refs_liked_why", type: "textarea", label: "O que você gosta nesses sites?", help: "Pode ser as cores, o jeito de organizar, as fotos, o clima... Qualquer coisa que tenha chamado a sua atenção.", placeholder: "Cores, estilo, organização…", allowAudio: true },
      { id: "ref_disliked", type: "links", label: "Tem algum site de que você NÃO gosta? Cole o link", help: "Saber o que evitar ajuda tanto quanto saber o que você curte. Escolha um site que você acha feio, confuso ou que não tem nada a ver com você. Se não lembrar de nenhum, é só pular.", placeholder: "www.exemplo.com.br", maxItems: 1 },
      { id: "ref_disliked_why", type: "textarea", label: "O que te incomoda nesse site?", help: "Conte com as suas palavras o que te incomoda quando você abre esse site.", example: "muita informação junta, cores fortes demais, difícil de achar as coisas, parece antigo.", allowAudio: true },
    ],
  },
  {
    id: "tom",
    title: "Como a marca fala?",
    subtitle: "Imagine que a sua marca é uma pessoa falando com o cliente. Como ela fala?",
    estimatedMinutes: 1,
    questions: [
      { id: "tone_formality", type: "slider", label: "A sua marca é mais formal ou mais descontraída?", help: "Formal soa assim: \"Prezado cliente, temos o prazer de apresentar...\". Descontraído soa assim: \"Oi! Bora conhecer a gente?\".", leftLabel: "Formal", rightLabel: "Descontraído" },
      { id: "tone_seriousness", type: "slider", label: "Mais séria ou mais divertida?", help: "Séria passa credibilidade e calma. Divertida usa leveza e humor.", leftLabel: "Sério", rightLabel: "Divertido" },
      { id: "tone_price", type: "slider", label: "Mais luxo ou mais acessível?", help: "Luxo passa exclusividade e sofisticação. Acessível passa proximidade e preço justo.", leftLabel: "Luxo", rightLabel: "Acessível" },
    ],
  },
  {
    id: "conteudo",
    title: "Conteúdo do site",
    subtitle: "O que vai aparecer no site e quem vai preparar esse material.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "sections",
        type: "multi",
        label: "Quais seções você imagina no site?",
        help: "Seções são os \"blocos\" que o visitante vai ver ao rolar a página. Marque as que fizerem sentido. Se tiver dúvida, sugerimos depois.",
        options: [
          { value: "sobre", label: "Sobre", description: "Sua história e quem você é." },
          { value: "servicos", label: "Serviços", description: "O que você oferece." },
          { value: "precos", label: "Preços", description: "Valores ou planos." },
          { value: "depoimentos", label: "Depoimentos", description: "O que os clientes falam de você." },
          { value: "portfolio", label: "Portfólio", description: "Trabalhos que você já fez." },
          { value: "faq", label: "FAQ", description: "Perguntas frequentes, já respondidas." },
          { value: "blog", label: "Blog", description: "Artigos e novidades." },
          { value: "contato", label: "Contato", description: "Formulário, telefone e mapa." },
          { value: "equipe", label: "Equipe", description: "Apresentação das pessoas do seu time." },
        ],
      },
      {
        id: "has_copy",
        type: "single",
        label: "Você já tem os textos do site?",
        help: "\"Copywriting\" é escrever os textos de forma que convençam quem está visitando. Se você não tem nada pronto, podemos escrever junto com você.",
        options: [
          { value: "tenho", label: "Tenho os textos prontos" },
          { value: "parte", label: "Tenho uma parte" },
          { value: "copywriting", label: "Preciso de copywriting" },
        ],
      },
      {
        id: "has_photos",
        type: "single",
        label: "E as fotos e imagens?",
        help: "Fotos reais da sua empresa, produtos e equipe deixam o site mais confiável. \"Banco de imagens\" são fotos profissionais prontas para usar.",
        options: [
          { value: "tenho", label: "Tenho fotos boas" },
          { value: "banco", label: "Preciso de banco de imagens" },
          { value: "fotografar", label: "Vou fotografar" },
        ],
      },
    ],
  },
  {
    id: "funcionalidades",
    title: "Funcionalidades",
    subtitle: "O que o site precisa fazer, além de mostrar informações. Não precisa entender de tecnologia: marque o que fizer sentido.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "features",
        type: "multi",
        label: "O que o site precisa ter?",
        help: "Marque as funções que você quer. Se não entender alguma, deixe em branco que explicamos depois.",
        options: [
          { value: "whatsapp", label: "Botão WhatsApp", description: "Um botão que abre uma conversa com você." },
          { value: "form", label: "Formulário de contato", description: "O visitante preenche e você recebe no e-mail." },
          { value: "agendamento", label: "Agendamento", description: "O cliente escolhe dia e horário." },
          { value: "pagamento", label: "Pagamento online", description: "Cartão, Pix ou boleto direto no site." },
          { value: "crm", label: "CRM", description: "Um sistema que organiza seus contatos e vendas." },
          { value: "analytics", label: "Analytics", description: "Números de quantas pessoas visitam o site." },
          { value: "chat", label: "Chat", description: "Uma janelinha de conversa no site." },
          { value: "blog", label: "Blog", description: "Espaço para você publicar artigos." },
          { value: "idiomas", label: "Multi-idioma", description: "Site disponível em mais de um idioma." },
          { value: "membros", label: "Área de membros", description: "Uma parte do site com login, só para clientes." },
        ],
      },
      { id: "integrations", type: "textarea", label: "Precisa se conectar com alguma ferramenta que você já usa?", help: "Por exemplo: sistema de e-mail marketing, agenda, meio de pagamento, planilhas. Se não usa nenhuma, pode pular.", example: "Mailchimp, Google Agenda, Mercado Pago.", placeholder: "Ex.: planilha, e-mail marketing, ERP…", allowAudio: true },
    ],
  },
  {
    id: "infra",
    title: "Domínio e hospedagem",
    subtitle: "Onde o site vai morar na internet. Se você não sabe nada disso, tudo bem: é só marcar \"Não sei\".",
    estimatedMinutes: 1,
    questions: [
      {
        id: "has_domain",
        type: "single",
        label: "Você já tem um domínio?",
        help: "Domínio é o endereço do seu site na internet, como \"suaempresa.com.br\". Se você já comprou um, marque \"Sim\".",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim" },
          { value: "nao", label: "Não" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
      {
        id: "domain_registrar",
        type: "text",
        label: "Onde você registrou esse domínio?",
        help: "É o site em que você comprou o endereço. Se não lembra, procure no e-mail da compra ou marque \"Não sei\".",
        example: "Registro.br, GoDaddy, Hostinger.",
        placeholder: "Ex.: Registro.br, GoDaddy…",
        allowUnknown: true,
        showIf: { field: "has_domain", equals: "sim" },
      },
      {
        id: "has_hosting",
        type: "single",
        label: "Você já tem hospedagem?",
        help: "Hospedagem é o \"terreno\" onde o site fica guardado para ficar disponível na internet. Se você não sabe, marque \"Não sei\" e nós cuidamos disso.",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim, tenho" },
          { value: "nao", label: "Não tenho" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
      {
        id: "who_maintains",
        type: "single",
        label: "Quem vai cuidar do site depois de pronto?",
        help: "Depois de publicado, o site precisa de pequenas atualizações e cuidados. Você pode fazer por conta própria ou contratar uma manutenção mensal.",
        allowUnknown: true,
        options: [
          { value: "eu", label: "Eu mesmo" },
          { value: "mensal", label: "Preciso de manutenção mensal" },
          { value: "nao_sei", label: "Não sei ainda" },
        ],
      },
    ],
  },
  {
    id: "prazo",
    title: "Prazo e investimento",
    subtitle: "Ajuda a planejarmos o projeto de forma realista. Sem compromisso.",
    estimatedMinutes: 1,
    questions: [
      {
        id: "deadline",
        type: "single",
        label: "Para quando você precisa do projeto?",
        help: "Seja sincero: prazos muito curtos exigem mais dedicação e podem custar mais. Se não tem pressa, escolha \"Flexível\".",
        options: [
          { value: "urgente", label: "Urgente (menos de 2 semanas)" },
          { value: "1mes", label: "Em até 1 mês" },
          { value: "2-3meses", label: "Em 2–3 meses" },
          { value: "flexivel", label: "Flexível" },
        ],
      },
      { id: "deadline_date", type: "text", label: "Existe alguma data específica?", help: "Por exemplo, um lançamento, evento ou campanha. Se não tem uma data, é só pular.", placeholder: "Ex.: 15/12 (opcional)" },
      {
        id: "budget",
        type: "cards",
        label: "Quanto você pretende investir?",
        help: "Só uma faixa aproximada, sem nenhum compromisso. Ajuda a indicarmos a solução certa para o seu bolso. Se preferir não dizer agora, escolha \"Prefiro conversar\".",
        allowUnknown: true,
        unknownLabel: "Prefiro conversar",
        options: [
          { value: "faixa1", label: "Até R$ 2 mil", description: "Landing enxuta e direta." },
          { value: "faixa2", label: "R$ 2–5 mil", description: "Site completo e personalizado." },
          { value: "faixa3", label: "R$ 5–10 mil", description: "Projeto maior ou sistema." },
          { value: "faixa4", label: "Acima de R$ 10 mil", description: "Escopo amplo ou contínuo." },
        ],
      },
    ],
  },
  {
    id: "concorrentes",
    title: "Referências de mercado",
    subtitle: "Conhecer o mercado nos ajuda a fazer o seu site se destacar.",
    estimatedMinutes: 1,
    questions: [
      { id: "competitors", type: "links", label: "Quem são os seus principais concorrentes?", help: "São empresas que oferecem algo parecido com o que você faz. Cole os links dos sites delas. Não é para copiar: é para fazer você se destacar.", placeholder: "www.exemplo.com.br", maxItems: 5 },
      { id: "final_notes", type: "textarea", label: "Tem mais alguma coisa que devemos saber?", help: "Espaço livre para ideias, dúvidas, preferências ou restrições. Qualquer coisa que não coube nas perguntas anteriores.", placeholder: "Qualquer detalhe que não coube antes…", allowAudio: true },
    ],
  },
  {
    id: "uploads",
    title: "Arquivos",
    subtitle: "Opcional. Se não tiver nada agora, você pode enviar depois pelo mesmo link.",
    estimatedMinutes: 1,
    questions: [
      { id: "files_logo", type: "file", label: "Envie o seu logo", help: "Se puder, envie em PNG ou SVG com fundo transparente. Se só tiver uma foto ou print, serve também.", fileKind: "logo", maxItems: 3 },
      { id: "files_photos", type: "file", label: "Envie fotos", help: "Da sua empresa, produtos, equipe ou local. Não precisa escolher as melhores: mande as que tiver.", fileKind: "foto", maxItems: 10 },
      { id: "files_docs", type: "file", label: "Envie documentos", help: "Manual da marca, apresentações, textos, tabelas de preços... Tudo o que ajude a entendermos o seu negócio.", fileKind: "documento", maxItems: 5 },
    ],
  },

  // ---- Blocos condicionais ----
  {
    id: "saas",
    title: "Sobre o sistema",
    subtitle: "Perguntas específicas para SaaS e sistemas web.",
    estimatedMinutes: 2,
    showIf: { field: "project_type", equals: "saas" },
    questions: [
      { id: "saas_core_features", type: "textarea", label: "Quais as principais funções do sistema?", help: "Conte o que a pessoa vai poder fazer lá dentro. Não precisa ser técnico.", example: "Cadastrar clientes, emitir relatórios e receber lembretes.", placeholder: "O que o sistema precisa fazer?", allowAudio: true },
      { id: "saas_user_types", type: "textarea", label: "Quais tipos de usuário vão usar?", help: "Cada tipo de usuário pode ver e fazer coisas diferentes.", example: "Administrador, funcionário, cliente.", placeholder: "Ex.: admin, cliente, visitante…" },
      {
        id: "saas_plans",
        type: "single",
        label: "Como você pretende cobrar?",
        help: "Grátis: ninguém paga. Freemium: uma versão grátis e outra paga com mais recursos. Assinatura: mensalidade. Por uso: paga conforme utiliza.",
        allowUnknown: true,
        options: [
          { value: "gratis", label: "Grátis" },
          { value: "freemium", label: "Freemium" },
          { value: "assinatura", label: "Assinatura" },
          { value: "uso", label: "Por uso" },
          { value: "indefinido", label: "Ainda não definido" },
        ],
      },
      {
        id: "saas_social_login",
        type: "single",
        label: "Quer que as pessoas possam entrar com a conta do Google ou outra?",
        help: "Permite entrar com 1 clique, sem criar senha nova. Deixa o cadastro bem mais fácil.",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim" },
          { value: "nao", label: "Não" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
      { id: "saas_integrations", type: "textarea", label: "Precisa se conectar com outros sistemas?", help: "Por exemplo, para emitir nota fiscal, cobrar no cartão ou enviar e-mails automáticos.", placeholder: "APIs, gateways, ferramentas…" },
      { id: "saas_stack_pref", type: "text", label: "Tem preferência de tecnologia?", help: "Só responda se você já sabe (por exemplo, se tem um time técnico). Se não, marque \"Não sei\" que escolhemos a melhor opção para o seu caso.", placeholder: "Se tiver alguma", allowUnknown: true },
    ],
  },
  {
    id: "ecommerce",
    title: "Sobre a loja",
    subtitle: "Perguntas específicas para e-commerce.",
    estimatedMinutes: 1,
    showIf: { field: "project_type", equals: "ecommerce" },
    questions: [
      {
        id: "ecom_product_count",
        type: "single",
        label: "Quantos produtos você vai vender?",
        help: "Uma estimativa já serve. Isso ajuda a definir como organizar a loja.",
        options: [
          { value: "ate20", label: "Até 20" },
          { value: "20-100", label: "20 a 100" },
          { value: "100-500", label: "100 a 500" },
          { value: "500+", label: "Mais de 500" },
        ],
      },
      {
        id: "ecom_gateway",
        type: "multi",
        label: "Como você quer receber os pagamentos?",
        help: "\"Gateway\" é o serviço que processa o pagamento (como Mercado Pago ou Stripe). Se você não sabe, marque \"Não sei\".",
        allowUnknown: true,
        options: [
          { value: "pix", label: "Pix" },
          { value: "cartao", label: "Cartão de crédito" },
          { value: "boleto", label: "Boleto" },
          { value: "mercadopago", label: "Mercado Pago" },
          { value: "stripe", label: "Stripe" },
          { value: "outro", label: "Outro" },
        ],
      },
      {
        id: "ecom_shipping",
        type: "single",
        label: "Como vai ser a entrega?",
        help: "Correios, transportadora, retirada no local, entrega própria... Marque o que pretende usar.",
        options: [
          { value: "correios", label: "Correios/transportadora" },
          { value: "motoboy", label: "Entrega local / motoboy" },
          { value: "retirada", label: "Retirada no local" },
          { value: "digital", label: "Produto digital" },
        ],
      },
      {
        id: "ecom_stock",
        type: "single",
        label: "Como você controla o estoque?",
        help: "Se já usa planilha ou algum sistema, conte qual. Se não controla, tudo bem.",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim" },
          { value: "nao", label: "Não" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
    ],
  },
  {
    id: "local",
    title: "Sobre o atendimento local",
    subtitle: "Para quem recebe clientes na região.",
    estimatedMinutes: 1,
    showIf: {
      any: [
        { field: "region", equals: "local" },
        { field: "niche", equals: "servicos_locais" },
      ],
    },
    questions: [
      { id: "local_address", type: "text", label: "Qual o endereço do seu negócio?", help: "Vai aparecer no site e no mapa para o cliente te encontrar.", placeholder: "Rua, número, bairro, cidade" },
      { id: "local_hours", type: "text", label: "Quais os horários de funcionamento?", help: "Dias da semana e horários em que você atende ou responde.", example: "Segunda a sexta, das 8h às 18h.", placeholder: "Ex.: seg–sex, 9h às 18h" },
      { id: "local_area", type: "text", label: "Quais regiões você atende?", help: "Cidade, bairros ou até quantos quilômetros você atende.", example: "Sorocaba e região.", placeholder: "Bairros, cidades ou raio de entrega" },
      {
        id: "local_gmb",
        type: "single",
        label: "Você tem perfil no Google Meu Negócio?",
        help: "É a ficha da sua empresa que aparece no Google e no Google Maps quando alguém pesquisa por você. Ajuda a ser encontrado perto de você.",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim" },
          { value: "nao", label: "Não" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
    ],
  },
  {
    id: "redesign",
    title: "Sobre o site atual",
    subtitle: "O que não funciona hoje — e o que manter.",
    estimatedMinutes: 1,
    showIf: { field: "project_type", equals: "redesign" },
    questions: [
      { id: "redesign_problems", type: "textarea", label: "O que não funciona no seu site atual?", help: "Conte o que te incomoda.", example: "Parece antigo, é lento, é difícil de usar no celular, ninguém entra em contato.", allowAudio: true },
      {
        id: "redesign_analytics",
        type: "single",
        label: "Você tem acesso ao Google Analytics do site?",
        help: "É a ferramenta que mostra quantas pessoas visitam o site e o que fazem nele. Se tem, ajuda muito a melhorarmos o que já funciona.",
        allowUnknown: true,
        options: [
          { value: "sim", label: "Sim" },
          { value: "nao", label: "Não" },
          { value: "nao_sei", label: "Não sei" },
        ],
      },
    ],
  },
  {
    id: "legal",
    title: "Exigências do seu setor",
    subtitle: "Algumas áreas têm regras próprias de comunicação.",
    estimatedMinutes: 1,
    showIf: { field: "niche", in: ["saude", "juridico", "financeiro"] },
    questions: [
      {
        id: "legal_notice",
        type: "notice",
        label: "Aviso",
        help: "Na sua área existem regras sobre como se pode divulgar serviços na internet. Vamos cuidar disso junto com você.",
      },
      {
        id: "legal_notes",
        type: "textarea",
        label: "Existe alguma regra ou restrição da sua área que precisamos respeitar?",
        help: "Algumas profissões são fiscalizadas por conselhos (como CFM, OAB ou CVM) e têm regras sobre o que pode aparecer em site e propaganda. Conte se você conhece alguma. Se não, marque \"Não sei\" e verificamos.",
        placeholder: "Ex.: não posso divulgar antes/depois, preciso de termo de consentimento…",
        allowUnknown: true,
        unknownLabel: "Não sei, me oriente",
      },
    ],
  },
];

export const QUESTION_COUNT = STEPS.reduce((n, s) => n + s.questions.length, 0);
